client:
  type: closed # { open, closed }
  rate: 1000 # only used for open clients -- units are txn/s
 
site:
  server:
      - ["s101:8101"]
      - ["s201:8102"]
      - ["s301:8103"]
      - ["s401:8104"]
      - ["s501:8105"]
      - ["s601:8106"]
      - ["s701:8107"]
      - ["s801:8108"]
  client:
      - ["c1"]
      - ["c2"]
      - ["c3"]
      - ["c4"]
      - ["c5"]
      - ["c6"]
      - ["c7"]
      - ["c8"]
      - ["c9"]
      - ["c10"]
      - ["c11"]
      - ["c12"]
      - ["c13"]
      - ["c14"]
      - ["c15"]
      - ["c16"]
      - ["c17"]
      - ["c18"]
      - ["c19"]
      - ["c20"]
      - ["c21"]
      - ["c22"]
      - ["c23"]
      - ["c24"]
      - ["c25"]
      - ["c26"]
      - ["c27"]
      - ["c28"]
      - ["c29"]
      - ["c30"]
      - ["c31"]
      - ["c32"]
      - ["c33"]
      - ["c34"]
      - ["c35"]
      - ["c36"]
      - ["c37"]
      - ["c38"]
      - ["c39"]
      - ["c40"]
      - ["c41"]
      - ["c42"]
      - ["c43"]
      - ["c44"]
      - ["c45"]
      - ["c46"]
      - ["c47"]
      - ["c48"]
      - ["c49"]
      - ["c50"]
      - ["c51"]
      - ["c52"]
      - ["c53"]
      - ["c54"]
      - ["c55"]
      - ["c56"]
      - ["c57"]
      - ["c58"]
      - ["c59"]
      - ["c60"]
      - ["c61"]
      - ["c62"]
      - ["c63"]
      - ["c64"]
 
process:
  s101: svr-1
  s201: svr-2
  s301: svr-3
  s401: svr-4
  s501: svr-5
  s601: svr-6
  s701: svr-7
  s801: svr-8
  c1: cli-1
  c2: cli-2
  c3: cli-3
  c4: cli-4
  c5: cli-5
  c6: cli-6
  c7: cli-7
  c8: cli-8
  c9: cli-9
  c10: cli-10
  c11: cli-11
  c12: cli-12
  c13: cli-13
  c14: cli-14
  c15: cli-15
  c16: cli-16
  c17: cli-17
  c18: cli-18
  c19: cli-19
  c20: cli-20
  c21: cli-21
  c22: cli-22
  c23: cli-23
  c24: cli-24
  c25: cli-25
  c26: cli-26
  c27: cli-27
  c28: cli-28
  c29: cli-29
  c30: cli-30
  c31: cli-31
  c32: cli-32
  c33: cli-33
  c34: cli-34
  c35: cli-35
  c36: cli-36
  c37: cli-37
  c38: cli-38
  c39: cli-39
  c40: cli-40
  c41: cli-41
  c42: cli-42
  c43: cli-43
  c44: cli-44
  c45: cli-45
  c46: cli-46
  c47: cli-47
  c48: cli-48
  c49: cli-49
  c50: cli-50
  c51: cli-51
  c52: cli-52
  c53: cli-53
  c54: cli-54
  c55: cli-55
  c56: cli-56
  c57: cli-57
  c58: cli-58
  c59: cli-59
  c60: cli-60
  c61: cli-61
  c62: cli-62
  c63: cli-63
  c64: cli-64
 
host:
  svr-1: node-1
  svr-2: node-2
  svr-3: node-3
  svr-4: node-4
  svr-5: node-5
  svr-6: node-6
  svr-7: node-7
  svr-8: node-8
  cli-1: node-11
  cli-2: node-12
  cli-3: node-13
  cli-4: node-14
  cli-5: node-15
  cli-6: node-16
  cli-7: node-17
  cli-8: node-18
  cli-9: node-11
  cli-10: node-12
  cli-11: node-13
  cli-12: node-14
  cli-13: node-15
  cli-14: node-16
  cli-15: node-17
  cli-16: node-18
  cli-17: node-11
  cli-18: node-12
  cli-19: node-13
  cli-20: node-14
  cli-21: node-15
  cli-22: node-16
  cli-23: node-17
  cli-24: node-18
  cli-25: node-11
  cli-26: node-12
  cli-27: node-13
  cli-28: node-14
  cli-29: node-15
  cli-30: node-16
  cli-31: node-17
  cli-32: node-18
  cli-33: node-11
  cli-34: node-12
  cli-35: node-13
  cli-36: node-14
  cli-37: node-15
  cli-38: node-16
  cli-39: node-17
  cli-40: node-18
  cli-41: node-11
  cli-42: node-12
  cli-43: node-13
  cli-44: node-14
  cli-45: node-15
  cli-46: node-16
  cli-47: node-17
  cli-48: node-18
  cli-49: node-11
  cli-50: node-12
  cli-51: node-13
  cli-52: node-14
  cli-53: node-15
  cli-54: node-16
  cli-55: node-17
  cli-56: node-18
  cli-57: node-11
  cli-58: node-12
  cli-59: node-13
  cli-60: node-14
  cli-61: node-15
  cli-62: node-16
  cli-63: node-17
  cli-64: node-18
 
mode:
  cc: acc
  ab: none
  read_only: occ
  batch: false
  retry: 9
  ongoing: 1
 
n_concurrent: 100
