client:
  type: closed # { open, closed }
  rate: 1000 # only used for open clients -- units are txn/s

# site - partition map
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:8101"]
    - ["s201:8102"]
  client: # each line is a partition
    - ["c1"]
    - ["c2"]

# site_name - process_name map
process:
  s101: node-1
  s201: node-2
  c1: node-3
  c2: node-4

# process_name - host_addr map
host:
  node-0: node-0
  node-1: node-1
  node-2: node-2
  node-3: node-3
  node-4: node-4

mode:
  cc: none # concurrency control
  ab: none # atomic broadcast
  read_only: occ
  batch: false
  retry: 9
  ongoing: 1 # per client

n_concurrent: 100