#
# host machine
#   physical process as container  
#     logical site as a thread
# site --> process --> host
#   
# site: logical site (either as server/coordinator), which lives in a thread (may share thread 
# process 
# host is  

# site - partition map
site:
  server: # each line is a partition, the first is the master site_name:port
#    - ["s101:8000", "s201:8001", "s301:8002"]
#    - ["s102:8100", "s202:8101", "s302:8102"]
#    - ["s103:8200", "s203:8201", "s303:8202"]
    - ["s101:8101"]
    - ["s102:8102"]
#    - ["s103:8103"]
  client: # each line is a partition
<<<<<<< HEAD
    - ["c101"]
    - ["c102"]
    - ["c103"]
    - ["c104"]
    - ["c105"]
    - ["c106"]
    - ["c107"]
    - ["c108"]
    - ["c109"]
    - ["c110"]
    - ["c111"]
    - ["c112"]
    - ["c113"]
    - ["c114"]
    - ["c115"]
    - ["c116"]
=======
    - ["c1"]
    - ["c2"]
    - ["c3"]
    - ["c4"]
    - ["c5"]
    - ["c6"]
    - ["c7"]
    - ["c8"]
    - ["c9"]
    - ["c10"]
    - ["c11"]
    - ["c12"]
    - ["c13"]
    - ["c14"]
    - ["c15"]
    - ["c16"]
#    - ["c1", "c2"]
#    - ["c3", "c4"]
>>>>>>> 16c2syml

# site_name - process_name map
process:
  s101: localhost
  s102: localhost
#  s103: localhost
<<<<<<< HEAD
  c101: localhost
  c102: localhost
  c103: localhost
  c104: localhost
  c105: localhost
  c106: localhost
  c107: localhost
  c108: localhost
  c109: localhost 
  c110: localhost
  c111: localhost
  c112: localhost
  c113: localhost
  c114: localhost
  c115: localhost
  c116: localhost



=======
  c1: localhost
  c2: localhost
  c3: localhost
  c4: localhost
  c5: localhost
  c6: localhost
  c7: localhost
  c8: localhost
  c9: localhost
  c10: localhost
  c11: localhost
  c12: localhost
  c13: localhost
  c14: localhost
  c15: localhost
  c16: localhost
>>>>>>> 16c2syml


# process_name - host_addr map
host:
  localhost: 127.0.0.1

