
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:8000", "s201:8001", "s301:8002"]
    - ["s102:8010", "s202:8011", "s302:8012"]
    - ["s103:8020", "s203:8021", "s303:8023"]
    - ["s104:8030", "s204:8031", "s304:8032"]
    - ["s105:8040", "s205:8041", "s305:8042"]
    - ["s106:8050"]
    - ["s107:8060"]
    - ["s108:8070"]
    - ["s109:8080"]
    - ["s110:8090"]
  client: # each line is a partition
    - ["c101"]

process:
  s101: localhost
  s201: localhost
  s301: localhost
  s102: localhost
  s202: localhost
  s302: localhost
  s103: localhost
  s203: localhost
  s303: localhost
  s104: localhost
  s204: localhost
  s304: localhost
  s105: localhost
  s205: localhost
  s305: localhost
  s106: localhost
  s206: localhost
  s306: localhost
  s107: localhost
  s207: localhost
  s307: localhost
  s108: localhost
  s208: localhost
  s308: localhost
  s109: localhost
  s209: localhost
  s309: localhost
  s110: localhost
  s210: localhost
  s310: localhost
  c101: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1
