
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:8000", "s201:8001", "s301:8002"]
  client: # each line is a partition
    - ["c101"]

process:
  s101: localhost
  s201: p2
  s301: p3
  c101: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  p2: 127.0.0.1
  p3: 127.0.0.1

