
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:8000", "s201:8001", "s301:8002"]
    - ["s102:8010", "s202:8011", "s302:8012"]
  client: # each line is a partition
    - ["c101"]

process:
  s101: localhost
  s201: localhost
  s301: localhost
  s102: localhost
  s202: localhost
  s302: localhost
  c101: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1
