client:
  type: closed # { open, closed }
  rate: 1000 # only used for open clients -- units are txn/s
 
site:
  server:
      - ["s101:8101"]
      - ["s201:8102"]
      - ["s301:8103"]
      - ["s401:8104"]
      - ["s501:8105"]
      - ["s601:8106"]
      - ["s701:8107"]
      - ["s801:8108"]
  client:
      - ["c1"]
      - ["c2"]
      - ["c3"]
      - ["c4"]
      - ["c5"]
      - ["c6"]
      - ["c7"]
      - ["c8"]
      - ["c9"]
      - ["c10"]
      - ["c11"]
      - ["c12"]
      - ["c13"]
      - ["c14"]
      - ["c15"]
      - ["c16"]
      - ["c17"]
      - ["c18"]
      - ["c19"]
      - ["c20"]
      - ["c21"]
      - ["c22"]
      - ["c23"]
      - ["c24"]
      - ["c25"]
      - ["c26"]
      - ["c27"]
      - ["c28"]
      - ["c29"]
      - ["c30"]
      - ["c31"]
      - ["c32"]
      - ["c33"]
      - ["c34"]
      - ["c35"]
      - ["c36"]
      - ["c37"]
      - ["c38"]
      - ["c39"]
      - ["c40"]
      - ["c41"]
      - ["c42"]
      - ["c43"]
      - ["c44"]
      - ["c45"]
      - ["c46"]
      - ["c47"]
      - ["c48"]
      - ["c49"]
      - ["c50"]
      - ["c51"]
      - ["c52"]
      - ["c53"]
      - ["c54"]
      - ["c55"]
      - ["c56"]
      - ["c57"]
      - ["c58"]
      - ["c59"]
      - ["c60"]
      - ["c61"]
      - ["c62"]
      - ["c63"]
      - ["c64"]
      - ["c65"]
      - ["c66"]
      - ["c67"]
      - ["c68"]
      - ["c69"]
      - ["c70"]
      - ["c71"]
      - ["c72"]
      - ["c73"]
      - ["c74"]
      - ["c75"]
      - ["c76"]
      - ["c77"]
      - ["c78"]
      - ["c79"]
      - ["c80"]
      - ["c81"]
      - ["c82"]
      - ["c83"]
      - ["c84"]
      - ["c85"]
      - ["c86"]
      - ["c87"]
      - ["c88"]
      - ["c89"]
      - ["c90"]
      - ["c91"]
      - ["c92"]
      - ["c93"]
      - ["c94"]
      - ["c95"]
      - ["c96"]
      - ["c97"]
      - ["c98"]
      - ["c99"]
      - ["c100"]
      - ["c101"]
      - ["c102"]
      - ["c103"]
      - ["c104"]
      - ["c105"]
      - ["c106"]
      - ["c107"]
      - ["c108"]
      - ["c109"]
      - ["c110"]
      - ["c111"]
      - ["c112"]
      - ["c113"]
      - ["c114"]
      - ["c115"]
      - ["c116"]
      - ["c117"]
      - ["c118"]
      - ["c119"]
      - ["c120"]
      - ["c121"]
      - ["c122"]
      - ["c123"]
      - ["c124"]
      - ["c125"]
      - ["c126"]
      - ["c127"]
      - ["c128"]
      - ["c129"]
      - ["c130"]
      - ["c131"]
      - ["c132"]
      - ["c133"]
      - ["c134"]
      - ["c135"]
      - ["c136"]
      - ["c137"]
      - ["c138"]
      - ["c139"]
      - ["c140"]
      - ["c141"]
      - ["c142"]
      - ["c143"]
      - ["c144"]
      - ["c145"]
      - ["c146"]
      - ["c147"]
      - ["c148"]
      - ["c149"]
      - ["c150"]
      - ["c151"]
      - ["c152"]
      - ["c153"]
      - ["c154"]
      - ["c155"]
      - ["c156"]
      - ["c157"]
      - ["c158"]
      - ["c159"]
      - ["c160"]
      - ["c161"]
      - ["c162"]
      - ["c163"]
      - ["c164"]
      - ["c165"]
      - ["c166"]
      - ["c167"]
      - ["c168"]
      - ["c169"]
      - ["c170"]
      - ["c171"]
      - ["c172"]
      - ["c173"]
      - ["c174"]
      - ["c175"]
      - ["c176"]
      - ["c177"]
      - ["c178"]
      - ["c179"]
      - ["c180"]
      - ["c181"]
      - ["c182"]
      - ["c183"]
      - ["c184"]
      - ["c185"]
      - ["c186"]
      - ["c187"]
      - ["c188"]
      - ["c189"]
      - ["c190"]
      - ["c191"]
      - ["c192"]
      - ["c193"]
      - ["c194"]
      - ["c195"]
      - ["c196"]
      - ["c197"]
      - ["c198"]
      - ["c199"]
      - ["c200"]
      - ["c201"]
      - ["c202"]
      - ["c203"]
      - ["c204"]
      - ["c205"]
      - ["c206"]
      - ["c207"]
      - ["c208"]
      - ["c209"]
      - ["c210"]
      - ["c211"]
      - ["c212"]
      - ["c213"]
      - ["c214"]
      - ["c215"]
      - ["c216"]
      - ["c217"]
      - ["c218"]
      - ["c219"]
      - ["c220"]
      - ["c221"]
      - ["c222"]
      - ["c223"]
      - ["c224"]
      - ["c225"]
      - ["c226"]
      - ["c227"]
      - ["c228"]
      - ["c229"]
      - ["c230"]
      - ["c231"]
      - ["c232"]
      - ["c233"]
      - ["c234"]
      - ["c235"]
      - ["c236"]
      - ["c237"]
      - ["c238"]
      - ["c239"]
      - ["c240"]
      - ["c241"]
      - ["c242"]
      - ["c243"]
      - ["c244"]
      - ["c245"]
      - ["c246"]
      - ["c247"]
      - ["c248"]
      - ["c249"]
      - ["c250"]
      - ["c251"]
      - ["c252"]
      - ["c253"]
      - ["c254"]
      - ["c255"]
      - ["c256"]
 
process:
  s101: localhost
  s201: localhost
  s301: localhost
  s401: localhost
  s501: localhost
  s601: localhost
  s701: localhost
  s801: localhost
  c1: localhost
  c2: localhost
  c3: localhost
  c4: localhost
  c5: localhost
  c6: localhost
  c7: localhost
  c8: localhost
  c9: localhost
  c10: localhost
  c11: localhost
  c12: localhost
  c13: localhost
  c14: localhost
  c15: localhost
  c16: localhost
  c17: localhost
  c18: localhost
  c19: localhost
  c20: localhost
  c21: localhost
  c22: localhost
  c23: localhost
  c24: localhost
  c25: localhost
  c26: localhost
  c27: localhost
  c28: localhost
  c29: localhost
  c30: localhost
  c31: localhost
  c32: localhost
  c33: localhost
  c34: localhost
  c35: localhost
  c36: localhost
  c37: localhost
  c38: localhost
  c39: localhost
  c40: localhost
  c41: localhost
  c42: localhost
  c43: localhost
  c44: localhost
  c45: localhost
  c46: localhost
  c47: localhost
  c48: localhost
  c49: localhost
  c50: localhost
  c51: localhost
  c52: localhost
  c53: localhost
  c54: localhost
  c55: localhost
  c56: localhost
  c57: localhost
  c58: localhost
  c59: localhost
  c60: localhost
  c61: localhost
  c62: localhost
  c63: localhost
  c64: localhost
  c65: localhost
  c66: localhost
  c67: localhost
  c68: localhost
  c69: localhost
  c70: localhost
  c71: localhost
  c72: localhost
  c73: localhost
  c74: localhost
  c75: localhost
  c76: localhost
  c77: localhost
  c78: localhost
  c79: localhost
  c80: localhost
  c81: localhost
  c82: localhost
  c83: localhost
  c84: localhost
  c85: localhost
  c86: localhost
  c87: localhost
  c88: localhost
  c89: localhost
  c90: localhost
  c91: localhost
  c92: localhost
  c93: localhost
  c94: localhost
  c95: localhost
  c96: localhost
  c97: localhost
  c98: localhost
  c99: localhost
  c100: localhost
  c101: localhost
  c102: localhost
  c103: localhost
  c104: localhost
  c105: localhost
  c106: localhost
  c107: localhost
  c108: localhost
  c109: localhost
  c110: localhost
  c111: localhost
  c112: localhost
  c113: localhost
  c114: localhost
  c115: localhost
  c116: localhost
  c117: localhost
  c118: localhost
  c119: localhost
  c120: localhost
  c121: localhost
  c122: localhost
  c123: localhost
  c124: localhost
  c125: localhost
  c126: localhost
  c127: localhost
  c128: localhost
  c129: localhost
  c130: localhost
  c131: localhost
  c132: localhost
  c133: localhost
  c134: localhost
  c135: localhost
  c136: localhost
  c137: localhost
  c138: localhost
  c139: localhost
  c140: localhost
  c141: localhost
  c142: localhost
  c143: localhost
  c144: localhost
  c145: localhost
  c146: localhost
  c147: localhost
  c148: localhost
  c149: localhost
  c150: localhost
  c151: localhost
  c152: localhost
  c153: localhost
  c154: localhost
  c155: localhost
  c156: localhost
  c157: localhost
  c158: localhost
  c159: localhost
  c160: localhost
  c161: localhost
  c162: localhost
  c163: localhost
  c164: localhost
  c165: localhost
  c166: localhost
  c167: localhost
  c168: localhost
  c169: localhost
  c170: localhost
  c171: localhost
  c172: localhost
  c173: localhost
  c174: localhost
  c175: localhost
  c176: localhost
  c177: localhost
  c178: localhost
  c179: localhost
  c180: localhost
  c181: localhost
  c182: localhost
  c183: localhost
  c184: localhost
  c185: localhost
  c186: localhost
  c187: localhost
  c188: localhost
  c189: localhost
  c190: localhost
  c191: localhost
  c192: localhost
  c193: localhost
  c194: localhost
  c195: localhost
  c196: localhost
  c197: localhost
  c198: localhost
  c199: localhost
  c200: localhost
  c201: localhost
  c202: localhost
  c203: localhost
  c204: localhost
  c205: localhost
  c206: localhost
  c207: localhost
  c208: localhost
  c209: localhost
  c210: localhost
  c211: localhost
  c212: localhost
  c213: localhost
  c214: localhost
  c215: localhost
  c216: localhost
  c217: localhost
  c218: localhost
  c219: localhost
  c220: localhost
  c221: localhost
  c222: localhost
  c223: localhost
  c224: localhost
  c225: localhost
  c226: localhost
  c227: localhost
  c228: localhost
  c229: localhost
  c230: localhost
  c231: localhost
  c232: localhost
  c233: localhost
  c234: localhost
  c235: localhost
  c236: localhost
  c237: localhost
  c238: localhost
  c239: localhost
  c240: localhost
  c241: localhost
  c242: localhost
  c243: localhost
  c244: localhost
  c245: localhost
  c246: localhost
  c247: localhost
  c248: localhost
  c249: localhost
  c250: localhost
  c251: localhost
  c252: localhost
  c253: localhost
  c254: localhost
  c255: localhost
  c256: localhost
 
host:
  localhost: 127.0.0.1
