
site:
  server: # each line is a partition, the first is the master site_name:port
#    - ["s101:8000", "s201:8001", "s301:8002"]
#    - ["s102:8100", "s202:8101", "s302:8102"]
#    - ["s103:8200", "s203:8201", "s303:8202"]
    - ["s101:8101"]
    - ["s102:8102"]
    - ["s103:8103"]
    - ["s104:8104"]
  client: # each line is a partition
    - ["c01"]
    - ["c02"]
    - ["c03"]
    - ["c04"]

# site_name - process_name map
process:
  s101: localhost
  s102: localhost
  s103: localhost
  s104: localhost
  c01: localhost
  c02: localhost
  c03: localhost
  c04: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1
