
#include "piece.h"

namespace rococo {

void TpccRealDistPiece::RegPayment() {
  TpccPiece::RegPayment();
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_0,
            TPCC_TB_DISTRICT, TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_1,
            TPCC_TB_DISTRICT, TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_2,
            TPCC_TB_DISTRICT, TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_3,
            TPCC_TB_CUSTOMER, TPCC_VAR_C_D_ID, TPCC_VAR_C_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_4,
            TPCC_TB_CUSTOMER, TPCC_VAR_C_D_ID, TPCC_VAR_C_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_5,
            TPCC_TB_HISTORY, TPCC_VAR_H_KEY);
}

void TpccRealDistPiece::RegNewOrder() {
  TpccPiece::RegNewOrder();
  SHARD_PIE(TPCC_NEW_ORDER, TPCC_NEW_ORDER_0,
            TPCC_TB_DISTRICT, TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_NEW_ORDER, TPCC_NEW_ORDER_1,
            TPCC_TB_DISTRICT, TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_NEW_ORDER, TPCC_NEW_ORDER_2,
            TPCC_TB_CUSTOMER, TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_NEW_ORDER, TPCC_NEW_ORDER_3,
            TPCC_TB_ORDER, TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_NEW_ORDER, TPCC_NEW_ORDER_4,
            TPCC_TB_NEW_ORDER, TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  for (int i = (0); i < (1000); i++) {
    // 1000 is a magical number?
    SHARD_PIE(TPCC_NEW_ORDER, TPCC_NEW_ORDER_RI(i),
              TPCC_TB_ITEM, TPCC_VAR_I_ID(i), TPCC_VAR_S_W_ID(i))
    SHARD_PIE(TPCC_NEW_ORDER, TPCC_NEW_ORDER_RS(i),
              TPCC_TB_STOCK, TPCC_VAR_I_ID(i), TPCC_VAR_S_W_ID(i))
    SHARD_PIE(TPCC_NEW_ORDER, TPCC_NEW_ORDER_WS(i),
              TPCC_TB_STOCK, TPCC_VAR_I_ID(i), TPCC_VAR_S_W_ID(i))
    SHARD_PIE(TPCC_NEW_ORDER, TPCC_NEW_ORDER_WOL(i),
              TPCC_TB_ORDER_LINE, TPCC_VAR_D_ID, TPCC_VAR_W_ID)

  }
}

void TpccRealDistPiece::RegDelivery() {
  TpccPiece::RegDelivery();
  SHARD_PIE(TPCC_DELIVERY, TPCC_DELIVERY_0, TPCC_TB_NEW_ORDER,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_DELIVERY, TPCC_DELIVERY_1, TPCC_TB_ORDER,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_DELIVERY, TPCC_DELIVERY_2, TPCC_TB_ORDER_LINE,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_DELIVERY, TPCC_DELIVERY_3, TPCC_TB_CUSTOMER,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
}

void TpccRealDistPiece::RegOrderStatus() {
  TpccPiece::RegOrderStatus();
  SHARD_PIE(TPCC_ORDER_STATUS, TPCC_ORDER_STATUS_0, TPCC_TB_CUSTOMER,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_ORDER_STATUS, TPCC_ORDER_STATUS_1, TPCC_TB_CUSTOMER,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_ORDER_STATUS, TPCC_ORDER_STATUS_2, TPCC_TB_ORDER,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_ORDER_STATUS, TPCC_ORDER_STATUS_3, TPCC_TB_ORDER_LINE,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
}

void TpccRealDistPiece::RegStockLevel() {
  TpccPiece::RegStockLevel();
  SHARD_PIE(TPCC_STOCK_LEVEL, TPCC_STOCK_LEVEL_0, TPCC_TB_DISTRICT,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_STOCK_LEVEL, TPCC_STOCK_LEVEL_1, TPCC_TB_ORDER_LINE,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  for (int i = (0); i < (1000); i++) {
    SHARD_PIE(TPCC_STOCK_LEVEL, TPCC_STOCK_LEVEL_RS(i), TPCC_TB_STOCK,
              TPCC_VAR_OL_I_ID(i), TPCC_VAR_W_ID)
  }
}

} // namespace rococo