
#include "piece.h"

namespace rococo {

void TpccRealDistPiece::RegPayment() {
  TpccPiece::RegPayment();
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_0,
            TPCC_TB_DISTRICT, TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_1,
            TPCC_TB_DISTRICT, TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_2,
            TPCC_TB_DISTRICT, TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_3,
            TPCC_TB_CUSTOMER, TPCC_VAR_C_D_ID, TPCC_VAR_C_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_4,
            TPCC_TB_CUSTOMER, TPCC_VAR_C_D_ID, TPCC_VAR_C_W_ID);
  SHARD_PIE(TPCC_PAYMENT, TPCC_PAYMENT_5,
            TPCC_TB_HISTORY, TPCC_VAR_H_KEY);
}

} // namespace rococo