
#include "piece.h"

namespace rococo {

void TpccRealDistPiece::RegOrderStatus() {
  TpccPiece::RegOrderStatus();
  SHARD_PIE(TPCC_ORDER_STATUS, TPCC_ORDER_STATUS_0, TPCC_TB_CUSTOMER,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID);
  SHARD_PIE(TPCC_ORDER_STATUS, TPCC_ORDER_STATUS_1, TPCC_TB_CUSTOMER,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_ORDER_STATUS, TPCC_ORDER_STATUS_2, TPCC_TB_ORDER,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_ORDER_STATUS, TPCC_ORDER_STATUS_3, TPCC_TB_ORDER_LINE,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
}

void TpccRealDistPiece::RegStockLevel() {
  TpccPiece::RegStockLevel();
  SHARD_PIE(TPCC_STOCK_LEVEL, TPCC_STOCK_LEVEL_0, TPCC_TB_DISTRICT,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  SHARD_PIE(TPCC_STOCK_LEVEL, TPCC_STOCK_LEVEL_1, TPCC_TB_ORDER_LINE,
            TPCC_VAR_D_ID, TPCC_VAR_W_ID)
  for (int i = (0); i < (1000); i++) {
    SHARD_PIE(TPCC_STOCK_LEVEL, TPCC_STOCK_LEVEL_RS(i), TPCC_TB_STOCK,
              TPCC_VAR_OL_I_ID(i), TPCC_VAR_W_ID)
  }
}

} // namespace rococo
