hunter_config(
        Boost
        VERSION ${HUNTER_Boost_VERSION}
#        VERSION 1.68.0-p1
#        CMAKE_ARGS
#        CONFIG_MACRO=BOOST_REGEX_MATCH_EXTRA;BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
#        CONFIG_MACRO_BOOST_MPL_LIMIT_LIST_SIZE=3
#        CONFIG_MACRO=BOOST_USE_UCONTEXT;BOOST_USE_ASAN
#        COROUTINE_context-impl=ucontext
)
